services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn barbershop.wsgi:application --bind 0.0.0.0:$PORT"
    rootDir: backend # Asegúrate de que esta línea esté presente
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beardstyle-db
          property: connectionString
      - key: DEBUG
        value: "False"
    plan: free
  - type: web
    name: frontend
    env: node
    build:
      command: npm install && npm run build
    start:
      command: node server.js
    envVars:
      - key: NODE_VERSION
        value: 16
    staticPublishPath: dist
databases:
  - name: beardstyle-db
    plan: free
    region: oregon
